[package]
name = "code-merger-tauri"
version = "0.0.0"
description = "code-merger-tauri"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["devtools", "macos-private-api"] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-clipboard-manager = "2.1.0-beta.4"
tauri-plugin-dialog = "2.0.0-beta.9"
tokio = "1.37.0"
walkdir = "2.5.0"
window-vibrancy = "0.5.0"
tauri-plugin-os = "2.0.0-beta.6"
